#load @"include.system.collections.immutable.fsx" 
#load @"include.system.reflection.metadata.fsx" 
#r "../../../packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.dll" 
#r "../../../packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.MSBuild.v12.dll" 
printfn "fsharp.compiler.service Loaded" 