#r "../../../packages/Argu/lib/net40/Argu.dll" 
#r "../../../packages/Expecto/lib/net40/Expecto.dll" 
#r "../../../packages/System.Collections.Immutable/lib/netstandard1.0/System.Collections.Immutable.dll" 
#r "../../../packages/System.Reflection.Metadata/lib/netstandard1.1/System.Reflection.Metadata.dll" 
#r "../../../packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.dll" 
#r "../../../packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.MSBuild.v12.dll" 
printfn "Loaded group Main" 